<?php

    require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . '..' .
                 DIRECTORY_SEPARATOR . 'reliq'
                 . DIRECTORY_SEPARATOR
                 . 'autoload.php';

    /**
     * Test class for SelectManager.
     * Generated by PHPUnit on 2011-08-07 at 18:22:52.
     */
    class AutoLoadTest extends PHPUnit_Framework_TestCase {

        public function testAutoLoad() {
            $t = new \Reliq\Table('table', array('driver' => 'test'));

            new \Reliq\Managers\SelectManager($t);
        }
    }

?>
